name: xenome
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  # share: ^0.6.3+6
  cloud_firestore: ^0.12.10+2
  chewie: ^0.9.10
  image_picker: ^0.6.0+2
  firebase_storage: ^3.0.8
  flutter_webview_plugin: 0.3.10+1
  firebase_auth: ^0.15.0+1
  firebase_database: ^3.1.0
  google_sign_in: ^4.0.11
  uuid: ^2.0.0
  image: ^2.0.7
  path_provider: ^0.5.0+1
  font_awesome_flutter: ^8.5.0
  async: ^2.1.0
  hidden_drawer_menu:
  http: ^0.12.0+1
  intl:
  firebase_messaging: ^5.1.8
  location: ^2.3.3
  geocoder: ^0.1.2
  carousel_pro: ^1.0.0
  parallax_image:
  circular_profile_avatar: ^1.0.2
  load: 0.1.5+1
  scoped_model:
  timezone:
  shared_preferences: ^0.4.3
  flutter_colorpicker: ^0.2.6
  flutter_flip_view: ^1.0.3
  auto_size_text: ^2.1.0
  percent_indicator: ^2.1.1+1
  syncfusion_flutter_charts: ^17.4.40
  youtube_player_flutter: ^6.0.3+2
  # flutter_youtube: ^1.1.6
  flutter_youtube: ^2.0.0
  # video_player: ^0.10.11+1
  flutter_svg: ^0.17.1
  flutter_local_notifications: ^0.7.1+1
  fluttertoast: ^3.1.0
  link: ^1.0.0
  url_launcher: ^5.4.10
  transparent_image: ^1.0.0
  simple_animations: ^2.2.1
  sa_multi_tween: ^1.1.1
  cached_network_image: ^2.0.0
  mailer2: ^1.2.5
  # flutter_youtube:
  #   path: ../test/plugins/FlutterYoutube
  flag: ^1.0.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  carousel_slider: ^1.3.0
  firebase_dynamic_links: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icos/
    - videos/IntroVideo.mp4
    - videos/small.mp4

    - assets/icos/play.svg
    - assets/icos/vimeo.svg
    - assets/icos/youtube.svg
    - assets/icos/instagram.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          #style: italic
          weight: 700
    #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
